<?php
/* LISTA DE PAISES*/
$tsPaises = array(
    'DE' => 'Alemania',
    'AR' => 'Argentina',
	'BO' => 'Bolivia',
    'BR' => 'Brasil',
    'CA' => 'Canad&aacute;',
    'CL' => 'Chile',
    'CO' => 'Colombia',
    'CR' => 'Costa Rica',
    'CU' => 'Cuba',
    'EC' => 'Ecuador',
    'SV' => 'El Salvador',
    'ES' => 'Espa&ntilde;a',
    'US' => 'Estados Unidos',
    'FR' => 'Francia',
    'GT' => 'Guatemala',
    'IT' => 'Italia',
    'JM' => 'Jamaica',
    'JP' => 'Jap&oacute;n',
    'MX' => 'M&eacute;xico',
    'NI' => 'Nicaragua',
    'PA' => 'Panam&aacute;',
    'PY' => 'Paraguay',
    'PE' => 'Per&uacute;',
    'PT' => 'Portugal',
    'PR' => 'Puerto Rico',
    'GB' => 'Reino Unido',
    'UY' => 'Uruguay',
    'VE' => 'Venezuela',
);	// MESES
	$tsMeces = array(
		1 => 'Enero',
		2 => 'Febrero',
		3 => 'Marzo',
		4 => 'Abril',
		5 => 'Mayo',
		6 => 'Junio',
		7 => 'Julio',
		8 => 'Agosto',
		9 => 'Septiembre',
		10 => 'Octubre',
		11 => 'Noviembre',
		12 => 'Diciembre',
	);
	/*********** PERFIL *******************/
	$tsPerfilData = array(
		/* GUSTOS */
		'gustos' => array(
			'Hacer amigos',
			'Conocer gente con mis intereses',
			'Conocer gente para negocios',
			'Encontrar pareja',
			'De todo'
		),
		/* ESTADO CIVIL */
		'estado' => array(
			'Sin Respuesta',
			'Soltero/a',
			'Con novio/a',
			'Casado/a',
			'Divorciado/a',
			'Viudo/a',
			'En algo...'
		),
		/* HIJOS */
		'hijos' => array(
			'Sin Respuesta',
			'No tengo',
			'Alg&uacute;n d&iacute;a',
			'No son lo m&iacute;o',
			'Tengo, vivo con ellos',
			'Tengo, no vivo con ellos'
		),
		/* VIVO CON */
		'vivo' => array(
			'Sin Respuesta',
			'S&oacute;lo',
			'Con mis padres',
			'Con mi pareja',
			'Con amigos',
			'Otro'
		),
		/* CABELLO */
		'pelo' => array(
			'Sin Respuesta',
			'Negro',
			'Casta&ntilde;o oscuro',
			'Casta&ntilde;o claro',
			'Rubio',
			'Pelirrojo',
			'Gris',
			'Verde',
			'Naranja',
			'Morado',
			'Azul',
			'Canoso',
			'Te&ntilde;ido',
			'Rapado',
			'Calvo',
		),
		/* OJOS */
		'ojos' => array(
			'Sin Respuesta',
			'Negros',
			'Marrones',
			'Celestes',
			'Verdes',
			'Grises',
		),
		/* COMPLEXION */
		'fisico' => array(
			'Sin Respuesta',
			'Delgado/a',
			'Atl&eacute;tico',
			'Normal',
			'Algunos kilos de m&aacute;s',
			'Corpulento/a',
		),
		/* DIETA */
		'dieta' => array(
			'Sin Respuesta',
			'Vegetariana',
			'Lacto Vegetariana',
			'Org&aacute;nica',
			'De todo',
			'Comida basura',
		),
		/* TENGO */
		'tengo' => array(
			'Tatuajes',
			'Piercings',
		),
		/* FUMO/TOMAR */
		'fumo_tomo' => array(
			'Sin Respuesta',
			'No',
			'Casualmente',
			'Socialmente',
			'Regularmente',
			'Mucho',
		),
		/* ESTUDIOS */
		'estudios' => array(
			'Sin Respuesta',
			'Sin Estudios',
			'Primario completo',
			'Secundario en curso',
			'Secundario completo',
			'Terciario en curso',
			'Terciario completo',
			'Universitario en curso',
			'Universitario completo',
			'Post-grado en curso',
			'Post-grado completo',
		),
		/* IDIOMAS */
		'idiomas' => array(
			'Espa&ntilde;ol',
			'Ingl&eacute;s',
			'Portugu&eacute;s',
			'Franc&eacute;s',
			'Italiano',
			'Alem&aacute;n',
			'Otro',
		),
		/* NIVEL DE IDIOMA */
		'inivel' => array(
			'Sin Respuesta',
			'Sin conocimiento',
			'B&aacute;sico',
			'Intermedio',
			'Fluido',
			'Nativo',
		),
		/* SECTOR */
		'sector' => array(
			'Sin Respuesta',
				'Abastecimiento',
				'Administraci&oacute;n',
				'Apoderado Aduanal',
				'Asesor&iacute;a en Comercio Exterior',
				'Asesor&iacute;a Legal Internacional',
				'Asistente de Tr&aacute;fico',
				'Auditor&iacute;a',
				'Calidad',
				'Call Center',
				'Capacitaci&oacute;n Comercio Exterior',
				'Comercial',
				'Comercio Exterior',
				'Compras',
				'Compras Internacionales/Importaci&oacute;n',
				'Comunicaci&oacute;n Social',
				'Comunicaciones Externas',
				'Comunicaciones Internas',
				'Consultor&iacute;a',
				'Consultor&iacute;as Comercio Exterior',
				'Contabilidad',
				'Control de Gesti&oacute;n',
				'Creatividad',
				'Dise&ntilde;o',
				'Distribuci&oacute;n',
				'E-commerce',
				'Educaci&oacute;n',
				'Finanzas',
				'Finanzas Internacionales',
				'Gerencia / Direcci&oacute;n General',
				'Impuestos',
				'Ingenier&iacute;a',
				'Internet',
				'Investigaci&oacute;n y Desarrollo',
				'J&oacute;venes Profesionales',
				'Legal',
				'Log&iacute;stica',
				'Mantenimiento',
				'Marketing',
				'Medio Ambiente',
				'Mercadotecnia Internacional',
				'Multimedia',
				'Otra',
				'Pasant&iacute;as',
				'Periodismo',
				'Planeamiento',
				'Producci&oacute;n',
				'Producci&oacute;n e Ingenier&iacute;a',
				'Recursos Humanos',
				'Relaciones Institucionales / P&uacute;blicas',
				'Salud',
				'Seguridad Industrial',
				'Servicios',
				'Soporte T&eacute;cnico',
				'Tecnolog&iacute;a',
				'Tecnolog&iacute;as de la Informaci&oacute;n',
				'Telecomunicaciones',
				'Telemarketing',
				'Traducci&oacute;n',
				'Transporte',
				'Ventas',
				'Ventas Internacionales/Exportaci&oacute;n',
		),
		/* INGRESOS */
		'ingresos' => array(
			'Sin Respuesta',
			'Sin ingresos',
			'Bajos',
			'Intermedios',
			'Altos',
		)
	);
    // PRIVACIDAD
    $tsPrivacidad = array(
        'Nadie',
		'Usuarios que sigo y me siguen',
		'Usuarios que sigo o me siguen',
        'Mis seguidores',
		'Usuarios que sigo',
        'Usuarios registrados',
        'Todos'
    );
	/* DENUNCIAS */
	$tsDenuncias = array(
        'users' => array(
            '',
            'Perfil falso/clon',
            'Usuario insultante y agresivo',
            'Publicaciones inapropiadas',
            'Foto del perfil inapropiada',
            'Publicidad no deseada (SPAM)',
        ),
        'posts' => array(
            '',
    		'Re-post',
    		'Se hace Spam',
    		'Tiene links muertos',
    		'Es racista o irrespetuoso',
    		'Contiene informaci&oacute;n personal',
    		'El t&iacute;tulo esta en may&uacute;scula',
    		'Contiene pedofilia',
    		'Es gore o asqueroso',
    		'Est&aacute; mal la fuente',
    		'Post demasiado pobre / Crap',
    		$tsCore->settings['titulo'].' no es un foro',
    		'No cumple con el protocolo',
    		'Otra raz&oacute;n (especificar)'
      ),
	  'comunidades' => array(
	  		'',
    		'Se hace Spam',
    		'Es racista o irrespetuosa',
    		'Contiene informaci&oacute;n personal',
    		'Contiene pedofilia',
    		'Es gore o asquerosa',
    		'No cumple con el protocolo',
    		'Otra raz&oacute;n (especificar)'
	  ),
	  'temas' => array(
	  		'',
    		'Re-post',
    		'Se hace Spam',
    		'Es racista o irrespetuoso',
    		'Contiene informaci&oacute;n personal',
    		'El t&iacute;tulo esta en may&uacute;scula',
    		'Contiene pedofilia',
    		'Es gore o asqueroso',
    		'No cumple con el protocolo',
    		'Otra raz&oacute;n (especificar)'
	  )
	);