<?php
$estados['DE'] = array(1 => 'Baden-W&uuml;rttemberg',3 => 'Bremen',4 => 'Freie und Hansestadt Hamburg',2 => 'Freistaat Bayern',13 => 'Freistaat Sachsen',15 => 'Freistaat Th&uuml;ringen',16 => 'Land Berlin',11 => 'Land Brandenburg',5 => 'Land Hessen',12 => 'Land Mecklenburg-Vorpommern',6 => 'Land Niedersachsen',7 => 'Land Nordrhein-Westfalen',14 => 'Land Sachsen-Anhalt',10 => 'Land Schleswig-Holstein',8 => 'Rheinland-Pfalz',9 => 'Saarland');
$estados['AR'] = array(1 => 'Buenos Aires',2 => 'Catamarca',5 => 'C&oacute;rdoba',3 => 'Chaco',4 => 'Chubut',7 => 'Ciudad Auton&oacute;ma de Buenos Aires',6 => 'Corrientes',8 => 'Entre R&iacute;os',9 => 'Formosa',10 => 'Jujuy',11 => 'La Pampa',12 => 'La Rioja',13 => 'Mendoza',14 => 'Misiones',15 => 'Neuqu&eacute;n',16 => 'R&iacute;o Negro',17 => 'Salta',18 => 'San Juan',19 => 'San Luis',20 => 'Santa Cruz',21 => 'Santa Fe',22 => 'Santiago del Estero',23 => 'Tierra del Fuego',24 => 'Tucum&aacute;n');
$estados['BO'] = array(1 => 'Chuquisaca',2 => 'Cochabamba',3 => 'Departamento del Beni',4 => 'La Paz',5 => 'Oruro',6 => 'Pando',7 => 'Potos&iacute;',8 => 'Santa Cruz',9 => 'Tarija');
$estados['BR'] = array(1 => 'Acre',2 => 'Alagoas',3 => 'Amap&aacute;',4 => 'Amazonas',5 => 'Bahia',6 => 'Cear&aacute;',7 => 'Distrito Federal',8 => 'Esp&iacute;rito Santo',29 => 'Goi&aacute;s',13 => 'Maranh&atilde;o',14 => 'Mato Grosso',11 => 'Mato Grosso do Sul',15 => 'Minas Gerais',17 => 'Para&iacute;ba',18 => 'Parana',16 => 'Par&aacute;',30 => 'Pernambuco',20 => 'Piau&iacute;',21 => 'Rio de Janeiro',22 => 'Rio Grande do Norte',23 => 'Rio Grande do Sul',24 => 'Rond&ocirc;nia',25 => 'Roraima',26 => 'Santa Catarina',27 => 'S&atilde;o Paulo',28 => 'Sergipe',31 => 'Tocantins');
$estados['CA'] = array(1 => 'Alberta',2 => 'British Columbia',3 => 'Manitoba',4 => 'New Brunswick',5 => 'Newfoundland and Labrador',13 => 'Northwest Territories',7 => 'Nova Scotia',14 => 'Nunavut',8 => 'Ontario',9 => 'Prince Edward Island',10 => 'Qu&eacute;bec',11 => 'Saskatchewan',12 => 'Yukon');
$estados['CL'] = array(2 => 'Regi&oacute;n Ais&eacute;n del General Carlos Ib&aacute;&ntilde;ez del Campo',3 => 'Regi&oacute;n de Antofagasta',16 => 'Regi&oacute;n de Arica y Parinacota',5 => 'Regi&oacute;n de Atacama',7 => 'Regi&oacute;n de Coquimbo',4 => 'Regi&oacute;n de la Araucan&iacute;a',14 => 'Regi&oacute;n de Los Lagos',17 => 'Regi&oacute;n de Los R&iacute;os',10 => 'Regi&oacute;n de Magallanes y de la Ant&aacute;rtica Chilena',15 => 'Regi&oacute;n de Tarapac&aacute;',1 => 'Regi&oacute;n de Valpara&iacute;so',6 => 'Regi&oacute;n del Biob&iacute;o',8 => 'Regi&oacute;n del Libertador General Bernardo O&#039;Higgins',11 => 'Regi&oacute;n del Maule',12 => 'Regi&oacute;n Metropolitana de Santiago');
$estados['CO'] = array(2 => 'Antioquia',3 => 'Arauca',35 => 'Bol&iacute;var',36 => 'Boyac&aacute;',37 => 'Caldas',32 => 'Casanare',12 => 'C&oacute;rdoba',33 => 'Cundinamarca',1 => 'Departamento del Amazonas',4 => 'Departamento del Atl&aacute;ntico',8 => 'Departamento del Caquet&aacute;',9 => 'Departamento del Cauca',10 => 'Departamento del Cesar',11 => 'Departamento del Choc&oacute;',15 => 'Departamento del Guain&iacute;a',14 => 'Departamento del Guaviare',16 => 'Departamento del Huila',38 => 'Departamento del Magdalena',19 => 'Departamento del Meta',22 => 'Departamento del Putumayo',23 => 'Departamento del Quind&iacute;o',29 => 'Departamento del Valle del Cauca',30 => 'Departamento del Vaup&eacute;s',31 => 'Departamento del Vichada',34 => 'Distrito Capital de Bogot&aacute;',17 => 'La Guajira',20 => 'Nari&ntilde;o',21 => 'Norte de Santander',25 => 'Providencia y Santa Catalina, Archipi&eacute;lago de San Andr&eacute;s',24 => 'Risaralda',26 => 'Santander',27 => 'Sucre',28 => 'Tolima');
$estados['CR'] = array(1 => 'Provincia de Alajuela',2 => 'Provincia de Cartago',3 => 'Provincia de Guanacaste',4 => 'Provincia de Heredia',6 => 'Provincia de Lim&oacute;n',7 => 'Provincia de Puntarenas',8 => 'Provincia de San Jos&eacute;');
$estados['DM'] = array(2 => 'Saint Andrew',3 => 'Saint David',4 => 'Saint George',5 => 'Saint John',6 => 'Saint Joseph',7 => 'Saint Luke',8 => 'Saint Mark',9 => 'Saint Patrick',10 => 'Saint Paul',11 => 'Saint Peter');
$estados['EC'] = array(3 => 'Provincia de Bol&iacute;var',7 => 'Provincia de Cotopaxi',8 => 'Provincia de El Oro',9 => 'Provincia de Esmeraldas',24 => 'Provincia de Francisco de Orellana',1 => 'Provincia de Gal&aacute;pagos',11 => 'Provincia de Imbabura',12 => 'Provincia de Loja',13 => 'Provincia de Los R&iacute;os',14 => 'Provincia de Manab&iacute;',15 => 'Provincia de Morona Santiago',23 => 'Provincia de Napo',18 => 'Provincia de Pichincha',25 => 'Provincia de Santa Elena',26 => 'Provincia de Santo Domingo de los Ts&aacute;chilas',22 => 'Provincia de Sucumb&iacute;os',20 => 'Provincia de Zamora Chinchipe',2 => 'Provincia del Azuay',4 => 'Provincia del Ca&ntilde;ar',5 => 'Provincia del Carchi',6 => 'Provincia del Chimborazo',10 => 'Provincia del Guayas',17 => 'Provincia del Pastaza',19 => 'Provincia del Tungurahua');
$estados['SV'] = array(1 => 'Ahuachap&aacute;n',2 => 'Caba&ntilde;as',3 => 'Chalatenango',4 => 'Cuscatl&aacute;n',5 => 'La Libertad',6 => 'La Paz',7 => 'La Uni&oacute;n',8 => 'Moraz&aacute;n',9 => 'San Miguel',10 => 'San Salvador',12 => 'San Vicente',11 => 'Santa Ana',13 => 'Sonsonate',14 => 'Usulut&aacute;n');
$estados['ES'] = array(51 => 'Andaluc&iacute;a',55 => 'Castilla y Le&oacute;n',54 => 'Castilla-La Mancha',56 => 'Catalunya',61 => 'Ceuta',52 => 'Comunidad Aut&oacute;noma de Arag&oacute;n',53 => 'Comunidad Aut&oacute;noma de Canarias',39 => 'Comunidad Aut&oacute;noma de Cantabria',29 => 'Comunidad de Madrid',7 => 'Comunitat Aut&ograve;noma de les Illes Balears',60 => 'Comunitat Valenciana',59 => 'Euskal Autonomia Erkidegoa',57 => 'Extremadura',58 => 'Galicia',27 => 'La Rioja',32 => 'Navarra',34 => 'Principado de Asturias',31 => 'Regi&oacute;n de Murcia');
$estados['US'] = array(1 => 'Alabama',2 => 'Alaska',3 => 'Arizona',4 => 'Arkansas',5 => 'California',6 => 'Colorado',7 => 'Connecticut',8 => 'Delaware',10 => 'Florida',11 => 'Georgia',12 => 'Hawaii',13 => 'Idaho',14 => 'Illinois',15 => 'Indiana',16 => 'Iowa',17 => 'Kansas',18 => 'Kentucky',19 => 'Louisiana',20 => 'Maine',21 => 'Maryland',22 => 'Massachusetts',23 => 'Michigan',24 => 'Minnesota',25 => 'Mississippi',26 => 'Missouri',27 => 'Montana',28 => 'Nebraska',29 => 'Nevada',30 => 'New Hampshire',31 => 'New Jersey',32 => 'New Mexico',33 => 'New York',34 => 'North Carolina',35 => 'North Dakota',9 => 'of Columbia',36 => 'Ohio',37 => 'Oklahoma',38 => 'Oregon',39 => 'Pennsylvania',40 => 'Rhode Island',41 => 'South Carolina',42 => 'South Dakota',43 => 'Tennessee',44 => 'Texas',45 => 'Utah',46 => 'Vermont',47 => 'Virginia',48 => 'Washington',49 => 'West Virginia',50 => 'Wisconsin',51 => 'Wyoming');
$estados['FR'] = array(100 => 'R&eacute;gion Alsace',97 => 'R&eacute;gion Aquitaine',98 => 'R&eacute;gion Auvergne',101 => 'R&eacute;gion &Icirc;le-de-France',99 => 'R&eacute;gion Basse-Normandie',102 => 'R&eacute;gion Bourgogne',103 => 'R&eacute;gion Bretagne',104 => 'R&eacute;gion Centre',105 => 'R&eacute;gion Champagne-Ardenne',106 => 'R&eacute;gion Corse',107 => 'R&eacute;gion Franche-Comt&eacute;',108 => 'R&eacute;gion Haute-Normandie',109 => 'R&eacute;gion Languedoc-Roussillon',110 => 'R&eacute;gion Limousin',111 => 'R&eacute;gion Lorraine',112 => 'R&eacute;gion Midi-Pyr&eacute;n&eacute;es',113 => 'R&eacute;gion Nord-Pas-de-Calais',114 => 'R&eacute;gion Pays de la Loire',115 => 'R&eacute;gion Picardie',116 => 'R&eacute;gion Poitou-Charentes',117 => 'R&eacute;gion Provence-Alpes-C&ocirc;te d&#039;Azur',118 => 'R&eacute;gion Rh&ocirc;ne-Alpes');
$estados['GT'] = array(1 => 'Alta Verapaz',2 => 'Baja Verapaz',3 => 'Chimaltenango',4 => 'Chiquimula',12 => 'Departamento del Pet&eacute;n',14 => 'Departamento del Quich&eacute;',5 => 'El Progreso',6 => 'Escuintla',7 => 'Guatemala',8 => 'Huehuetenango',9 => 'Izabal',10 => 'Jalapa',11 => 'Jutiapa',13 => 'Quetzaltenango',15 => 'Retalhuleu',16 => 'Sacatep&eacute;quez',17 => 'San Marcos',18 => 'Santa Rosa',19 => 'Solol&aacute;',20 => 'Suchitep&eacute;quez',21 => 'Totonicap&aacute;n',22 => 'Zacapa');
$estados['IT'] = array(1 => 'Abruzzo',2 => 'Basilicata',3 => 'Calabria',4 => 'Campania',5 => 'Emilia-Romagna',6 => 'Friuli-Venezia Giulia',8 => 'Liguria',9 => 'Lombardia',14 => 'Regione Autonoma della Sardegna',15 => 'Regione Autonoma Siciliana',17 => 'Regione Autonoma Trentino-Alto Adige',19 => 'Regione Autonoma Valle d&#039;Aosta',20 => 'Regione del Veneto',7 => 'Regione Lazio',10 => 'Regione Marche',11 => 'Regione Molise',12 => 'Regione Piemonte',13 => 'Regione Puglia',18 => 'Regione Umbria',16 => 'Toscana');
$estados['JM'] = array(1 => 'Parish of Clarendon',2 => 'Parish of Hanover',17 => 'Parish of Kingston',4 => 'Parish of Manchester',7 => 'Parish of Portland',8 => 'Parish of Saint Andrew',9 => 'Parish of Saint Ann',10 => 'Parish of Saint Catherine',11 => 'Parish of Saint Elizabeth',12 => 'Parish of Saint James',13 => 'Parish of Saint Mary',14 => 'Parish of Saint Thomas',15 => 'Parish of Trelawny',16 => 'Parish of Westmoreland');
$estados['JP'] = array(1 => 'Aichi-ken',2 => 'Akita-ken',3 => 'Aomori-ken',30 => '&#332;ita-ken',32 => '&#332;saka-fu',4 => 'Chiba-ken',5 => 'Ehime-ken',6 => 'Fukui-ken',7 => 'Fukuoka-ken',8 => 'Fukushima-ken',9 => 'Gifu-ken',10 => 'Gumma-ken',11 => 'Hiroshima-ken',12 => 'Hokkaid&#333;',13 => 'Hy&#333;go-ken',14 => 'Ibaraki-ken',15 => 'Ishikawa-ken',16 => 'Iwate-ken',17 => 'Kagawa-ken',18 => 'Kagoshima-ken',19 => 'Kanagawa-ken',20 => 'K&#333;chi-ken',21 => 'Kumamoto-ken',22 => 'Ky&#333;to-fu',23 => 'Mie-ken',24 => 'Miyagi-ken',25 => 'Miyazaki-ken',26 => 'Nagano-ken',27 => 'Nagasaki-ken',28 => 'Nara-ken',29 => 'Niigata-ken',31 => 'Okayama-ken',47 => 'Okinawa-ken',33 => 'Saga-ken',34 => 'Saitama-ken',35 => 'Shiga-ken',36 => 'Shimane-ken',37 => 'Shizuoka-ken',40 => 'T&#333;ky&#333;-to',38 => 'Tochigi-ken',39 => 'Tokushima-ken',41 => 'Tottori-ken',42 => 'Toyama-ken',43 => 'Wakayama-ken',44 => 'Yamagata-ken',45 => 'Yamaguchi-ken',46 => 'Yamanashi-ken');
$estados['MX'] = array(1 => 'Aguascalientes',2 => 'Baja California',3 => 'Baja California Sur',4 => 'Campeche',5 => 'Chiapas',6 => 'Chihuahua',7 => 'Coahuila de Zaragoza',8 => 'Colima',9 => 'Distrito Federal',10 => 'Durango',11 => 'Guanajuato',12 => 'Guerrero',13 => 'Hidalgo',14 => 'Jalisco',15 => 'M&eacute;xico',16 => 'Michoac&aacute;n de Ocampo',17 => 'Morelos',18 => 'Nayarit',19 => 'Nuevo Le&oacute;n',20 => 'Oaxaca',21 => 'Puebla',22 => 'Quer&eacute;taro de Arteaga',23 => 'Quintana Roo',24 => 'San Luis Potos&iacute;',25 => 'Sinaloa',26 => 'Sonora',27 => 'Tabasco',28 => 'Tamaulipas',29 => 'Tlaxcala',30 => 'Veracruz',31 => 'Yucat&aacute;n',32 => 'Zacatecas');
$estados['NI'] = array(1 => 'Boaco',2 => 'Carazo',3 => 'Chinandega',4 => 'Chontales',5 => 'Estel&iacute;',6 => 'Granada',7 => 'Jinotega',8 => 'Le&oacute;n',9 => 'Madriz',10 => 'Managua',11 => 'Masaya',12 => 'Matagalpa',13 => 'Nueva Segovia',14 => 'R&iacute;o San Juan',17 => 'Regi&oacute;n Aut&oacute;noma Atl&aacute;ntico Norte',18 => 'Regi&oacute;n Aut&oacute;noma Atl&aacute;ntico Sur',15 => 'Rivas');
$estados['PA'] = array(9 => 'Comarca de San Blas',1 => 'Provincia de Bocas del Toro',2 => 'Provincia de Chiriqu&iacute;',3 => 'Provincia de Cocl&eacute;',4 => 'Provincia de Col&oacute;n',6 => 'Provincia de Herrera',7 => 'Provincia de Los Santos',8 => 'Provincia de Panam&aacute;',10 => 'Provincia de Veraguas',5 => 'Provincia del Dari&eacute;n');
$estados['PE'] = array(1 => 'Amazonas',2 => 'Ancash',3 => 'Apur&iacute;mac',4 => 'Arequipa',5 => 'Ayacucho',6 => 'Cajamarca',8 => 'Cusco',9 => 'Huancavelica',10 => 'Hu&aacute;nuco',11 => 'Ica',12 => 'Jun&iacute;n',13 => 'La Libertad',14 => 'Lambayeque',15 => 'Lima',16 => 'Loreto',17 => 'Madre de Dios',18 => 'Moquegua',19 => 'Pasco',20 => 'Piura',7 => 'Provincia Constitucional del Callao',15 => 'Provincia de Lima',21 => 'Puno',22 => 'San Mart&iacute;n',23 => 'Tacna',24 => 'Tumbes',25 => 'Ucayali');
$estados['PT'] = array(11 => 'Distrito da Guarda',2 => 'Distrito de Aveiro',8 => 'Distrito de &Eacute;vora',3 => 'Distrito de Beja',4 => 'Distrito de Braga',5 => 'Distrito de Bragan&ccedil;a',6 => 'Distrito de Castelo Branco',7 => 'Distrito de Coimbra',9 => 'Distrito de Faro',13 => 'Distrito de Leiria',14 => 'Distrito de Lisboa',16 => 'Distrito de Portalegre',18 => 'Distrito de Santar&eacute;m',19 => 'Distrito de Set&uacute;bal',20 => 'Distrito de Viana do Castelo',21 => 'Distrito de Vila Real',22 => 'Distrito de Viseu',17 => 'Distrito do Porto',10 => 'Regi&atilde;o Aut&oacute;noma da Madeira',23 => 'Regi&atilde;o Aut&oacute;noma dos A&ccedil;ores');
$estados['PR'] = array(1 => 'A&ntilde;asco',1 => 'Adjuntas',1 => 'Aguada',1 => 'Aguadilla',1 => 'Aguas Buenas',1 => 'Aibonito',1 => 'Arecibo',1 => 'Arroyo',1 => 'Barceloneta',1 => 'Barranquitas',1 => 'San Juan');
$estados['GB'] = array(1 => 'England',2 => 'Northern Ireland',3 => 'Scotland',4 => 'Wales');
$estados['UY'] = array(1 => 'Artigas',2 => 'Canelones',3 => 'Cerro Largo',4 => 'Colonia',5 => 'Durazno',6 => 'Flores',7 => 'Florida',8 => 'Lavalleja',9 => 'Maldonado',10 => 'Montevideo',11 => 'Paysand&uacute;',12 => 'R&iacute;o Negro',13 => 'Rivera',14 => 'Rocha',15 => 'Salto',16 => 'San Jos&eacute;',17 => 'Soriano',18 => 'Tacuaremb&oacute;',19 => 'Treinta y Tres');
$estados['VE'] = array(24 => 'Dependencias Federales',25 => 'Distrito Federal',1 => 'Estado Amazonas',2 => 'Estado Anzo&aacute;tegui',3 => 'Estado Apure',4 => 'Estado Aragua',5 => 'Estado Barinas',6 => 'Estado Bol&iacute;var',7 => 'Estado Carabobo',8 => 'Estado Cojedes',11 => 'Estado Falc&oacute;n',12 => 'Estado Gu&aacute;rico',13 => 'Estado Lara',14 => 'Estado M&eacute;rida',15 => 'Estado Miranda',16 => 'Estado Monagas',17 => 'Estado Nueva Esparta',18 => 'Estado Portuguesa',19 => 'Estado Sucre',20 => 'Estado T&aacute;chira',21 => 'Estado Trujillo',26 => 'Estado Vargas',22 => 'Estado Yaracuy',23 => 'Estado Zulia',9 => 'Territorio Federal Delta Amacuro');
?>